<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2016/02/29 06:45:35
return array(

  // sfNuSoapPlugin_module_libs

  // sfNuSoapPlugin_lib
  'nusoap_base' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/nusoap.php',
  'nusoap_client' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/nusoap.php',
  'soapclient' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/nusoap.php',
  'nusoap_fault' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/nusoap.php',
  'soap_fault' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/nusoap.php',
  'nusoap_parser' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/nusoap.php',
  'soap_parser' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/nusoap.php',
  'nusoap_server' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/nusoap.php',
  'soap_server' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/nusoap.php',
  'soap_transport_http' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/nusoap.php',
  'soapval' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/nusoap.php',
  'wsdl' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/nusoap.php',
  'nusoap_wsdlcache' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/class.wsdlcache.php',
  'wsdlcache' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/class.wsdlcache.php',
  'nusoap_xmlschema' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/nusoap.php',
  'xmlschema' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/nusoap.php',
  'sfnusoapclient' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/nusoap.php',
  'nusoap_client_mime' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/nusoapmime.php',
  'soapclientmime' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/nusoapmime.php',
  'nusoap_server_mime' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/nusoapmime.php',
  'nusoapservermime' => 'D:/GitHub/symfony/plugins/sfNuSoapPlugin/lib/model/nusoapmime.php',

  // sfPropelPlugin_module_libs

  // sfPropelPlugin_lib
  'sfmixer' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfMixer.class.php',
  'sfpropel' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropel.class.php',
  'sfpropelbehavior' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelBehavior.class.php',
  'sfpropeldata' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelData.class.php',
  'sfpropeldatabaseschema' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelDatabaseSchema.class.php',
  'sfpropelmanytomany' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelManyToMany.class.php',
  'sfpropelpager' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelPager.class.php',
  'sfpropelbehaviorbase' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorBase.php',
  'sfpropelbehaviori18n' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18n.php',
  'sfpropelbehaviori18ntranslation' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18nTranslation.php',
  'sfpropelbehaviorsymfony' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfony.php',
  'sfpropelbehaviorsymfonybehaviors' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfonyBehaviors.php',
  'sfpropelbehaviortimestampable' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorTimestampable.php',
  'sfpropeldatabase' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/database/sfPropelDatabase.class.php',
  'sfwebdebugpanelpropel' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/debug/sfWebDebugPanelPropel.class.php',
  'sfformfilterpropel' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/form/sfFormFilterPropel.class.php',
  'sfformpropel' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/form/sfFormPropel.class.php',
  'sfpropelformfiltergenerator' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormFilterGenerator.class.php',
  'sfpropelformgenerator' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormGenerator.class.php',
  'sfpropelgenerator' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php',
  'sfpropellogger' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/log/sfPropelLogger.class.php',
  'swift_propelspool' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/mailer/Swift_PropelSpool.class.php',
  'sfpropelroute' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRoute.class.php',
  'sfpropelroutecollection' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRouteCollection.class.php',
  'sfphing' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPhing.class.php',
  'sfphinglistener' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPhingListener.php',
  'sfpropelbasetask' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBaseTask.class.php',
  'sfpropelbuildallloadtask' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllLoadTask.class.php',
  'sfpropelbuildalltask' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllTask.class.php',
  'sfpropelbuildfilterstask' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFiltersTask.class.php',
  'sfpropelbuildformstask' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFormsTask.class.php',
  'sfpropelbuildmodeltask' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildModelTask.class.php',
  'sfpropelbuildschematask' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSchemaTask.class.php',
  'sfpropelbuildsqltask' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSqlTask.class.php',
  'sfpropelbuildtask' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildTask.class.php',
  'sfpropelconfiguredatabasetask' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelConfigureDatabaseTask.class.php',
  'sfpropeldatadumptask' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataDumpTask.class.php',
  'sfpropeldataloadtask' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataLoadTask.class.php',
  'sfpropelgenerateadmintask' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateAdminTask.class.php',
  'sfpropelgeneratemoduleforroutetask' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleForRouteTask.class.php',
  'sfpropelgeneratemoduletask' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleTask.class.php',
  'sfpropelgraphviztask' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGraphvizTask.class.php',
  'sfpropelinsertsqltask' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelInsertSqlTask.class.php',
  'sfpropelschematoxmltask' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToXmlTask.class.php',
  'sfpropelschematoymltask' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToYmlTask.class.php',
  'sftesterpropel' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/test/sfTesterPropel.class.php',
  'sfvalidatorpropelchoice' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelChoice.class.php',
  'sfvalidatorpropelunique' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelUnique.class.php',
  'sfwidgetformpropelchoice' => 'D:/GitHub/symfony/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelChoice.class.php',

  // project
  'baseform' => 'D:/GitHub/symfony/lib/form/BaseForm.class.php',

  // project_model

  // application
  'myuser' => 'D:/GitHub/symfony/apps/backend/lib/myUser.class.php',

  // modules
);
