propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  material:
    _attributes: { phpName: Material }
    ID: { phpName: Id, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    MATNR: { phpName: Matnr, type: VARCHAR, size: '20', required: false }
    MTART: { phpName: Mtart, type: VARCHAR, size: '4', required: false }
    MBRSH: { phpName: Mbrsh, type: VARCHAR, size: '255', required: false }
    MAKTX: { phpName: Maktx, type: VARCHAR, size: '255', required: false }
    MEINS: { phpName: Meins, type: VARCHAR, size: '3', required: false }
    MATKL: { phpName: Matkl, type: VARCHAR, size: '255', required: false }
